name: CI - General
on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'ops/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - 'ops/**'
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: cmd/atlas/go.mod
      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          args: --verbose

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: cmd/atlas/go.mod
      - name: Run sql tests
        run: go test -race ./...
        working-directory: sql
      - name: Run schemahcl tests
        run: go test -race ./...
        working-directory: schemahcl

  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: cmd/atlas/go.mod
      - name: Run cli tests
        run: go test -race ./...
        working-directory: cmd/atlas

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: cmd/atlas/go.mod
      - name: Run integration tests for HCL
        working-directory: internal/integration/hclsqlspec
        run: go test -race -count=2 -v ./...

  dialect-integration:
    needs: [lint, unit, cli, integration]
    uses: ./.github/workflows/ci-dialect.yaml
    secrets: inherit
